"""Self-contained HTML model report — the shareable artifact for a model.

Everything is rendered from data already stored on disk (meta + cached
insights); nothing is recomputed. All user-controlled strings are escaped.
"""

from html import escape
from typing import Any

from app.prediction.schemas import InsightsResponse
from app.training.schemas import ModelMeta

TOP_FEATURES = 10
TOP_IMPACTS = 5

STYLE = """
body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; color: #1e293b;
  max-width: 760px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
h1 { font-size: 1.5rem; margin-bottom: 0.2rem; }
h2 { font-size: 1.05rem; margin: 1.6rem 0 0.5rem; border-bottom: 1px solid #e2e8f0;
  padding-bottom: 0.25rem; }
.muted { color: #64748b; }
.small { font-size: 0.85rem; }
table { border-collapse: collapse; width: 100%; font-size: 0.9rem; }
td, th { text-align: left; padding: 0.3rem 0.6rem 0.3rem 0; vertical-align: top; }
th { color: #64748b; font-weight: 600; }
.bar-track { background: #eef2ff; border-radius: 4px; height: 12px; width: 220px; }
.bar-fill { background: #4f46e5; border-radius: 4px; height: 12px; }
.warning { background: #fffbeb; border: 1px solid #fcd34d; color: #92400e;
  border-radius: 8px; padding: 0.5rem 0.8rem; margin: 0.4rem 0; font-size: 0.9rem; }
.metric { display: inline-block; margin: 0.4rem 1.6rem 0.4rem 0; }
.metric .value { font-size: 1.5rem; font-weight: 700; }
.metric .label { font-size: 0.8rem; color: #64748b; max-width: 180px; }
footer { margin-top: 2rem; font-size: 0.8rem; color: #64748b;
  border-top: 1px solid #e2e8f0; padding-top: 0.75rem; }
"""


def build_report_html(meta: ModelMeta, insights: InsightsResponse | None) -> str:
    sections = [
        _header(meta),
        _metrics_section(meta),
        _validation_section(meta),
        _importance_section(meta),
        _impacts_section(insights),
        _warnings_section(meta),
        _settings_section(meta),
    ]
    body = "\n".join(s for s in sections if s)
    return (
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
        f"<title>Model report — {escape(meta.target_column)}</title>"
        f"<style>{STYLE}</style></head><body>{body}"
        "<footer>Generated by AutoML Studio. All scores are measured on rows the "
        "model never saw during training.</footer></body></html>"
    )


def _header(meta: ModelMeta) -> str:
    task = "Predicts a category" if meta.task == "classification" else "Predicts a number"
    rows = f"{meta.n_rows_used:,}" if meta.n_rows_used else "?"
    return (
        f"<h1>Predicting <em>{escape(meta.target_column)}</em></h1>"
        f"<p class='muted'>{escape(meta.dataset_name)} · {task} · trained on {rows} rows "
        f"· {escape(meta.created_at[:10])}</p>"
    )


def _metric(value: str, label: str) -> str:
    return (
        f"<span class='metric'><span class='value'>{value}</span><br>"
        f"<span class='label'>{escape(label)}</span></span>"
    )


def _metrics_section(meta: ModelMeta) -> str:
    m: dict[str, Any] = meta.metrics or {}
    parts: list[str] = []
    if meta.task == "classification":
        if isinstance(m.get("accuracy"), (int, float)):
            parts.append(_metric(f"{m['accuracy']:.0%}", "of test predictions were correct"))
        if isinstance(m.get("f1_weighted"), (int, float)):
            parts.append(_metric(f"{m['f1_weighted']:.0%}", "balanced score across categories (F1)"))
        if isinstance(m.get("roc_auc"), (int, float)):
            parts.append(_metric(f"{m['roc_auc']:.0%}", "ability to tell the categories apart (AUC)"))
    else:
        if isinstance(m.get("r2"), (int, float)):
            parts.append(_metric(f"{m['r2']}", "of variation explained (R², 1.0 is perfect)"))
        if isinstance(m.get("mae"), (int, float)):
            parts.append(_metric(f"{m['mae']:,}", "typical prediction error (MAE)"))
    if isinstance(m.get("cv_mean"), (int, float)) and isinstance(m.get("cv_std"), (int, float)):
        parts.append(
            _metric(f"{m['cv_mean']} ± {m['cv_std']}", "consistency across re-tests (cross-validation)")
        )
    comparisons = _baseline_comparisons(meta.task, m)
    return "<h2>How good is it?</h2>" + "".join(parts) + comparisons


def _baseline_comparisons(task: str, m: dict[str, Any]) -> str:
    key = "accuracy" if task == "classification" else "r2"
    rows = []
    for prefix, label in (("baseline_", "Always guessing the obvious"), ("linear_", "A basic statistical model")):
        value = m.get(f"{prefix}{key}")
        if isinstance(value, (int, float)):
            shown = f"{value:.0%}" if task == "classification" else f"{value}"
            rows.append(f"<tr><td>{label}</td><td>{shown}</td></tr>")
    if not rows:
        return ""
    return (
        "<p class='small muted'>For context, simpler approaches score:</p>"
        f"<table>{''.join(rows)}</table>"
    )


def _validation_section(meta: ModelMeta) -> str:
    m = meta.metrics or {}
    test_rows = m.get("test_rows")
    held = f" ({test_rows:,} rows)" if isinstance(test_rows, int) else ""
    if meta.time_column:
        gap = (
            f" A {meta.horizon}-row gap was left before the test period so a "
            f"{meta.horizon}-step-ahead target can't leak into it."
            if meta.horizon
            else ""
        )
        how = (
            f"Rows were ordered by <strong>{escape(meta.time_column)}</strong> and the "
            f"most recent 20% of rows{held} were held back for testing — the model "
            "never saw the future while learning." + gap
        )
    else:
        how = (
            f"A random 20% of rows{held} was held back before training and used only "
            "to measure the scores above."
        )
    return f"<h2>How it was tested</h2><p class='small'>{how}</p>"


def _importance_section(meta: ModelMeta) -> str:
    if not meta.importance:
        return ""
    top = meta.importance[:TOP_FEATURES]
    max_score = max(item.score for item in top) or 1.0
    rows = "".join(
        f"<tr><td>{escape(item.feature)}</td>"
        f"<td><div class='bar-track'><div class='bar-fill' "
        f"style='width:{100 * item.score / max_score:.0f}%'></div></div></td>"
        f"<td>{item.score:.0%}</td></tr>"
        for item in top
    )
    return (
        "<h2>What drives the predictions</h2>"
        "<p class='small muted'>The share of the model's decisions each column is "
        f"responsible for.</p><table>{rows}</table>"
    )


def _impacts_section(insights: InsightsResponse | None) -> str:
    if insights is None or not insights.impacts:
        return ""
    rows = "".join(
        f"<tr><td>{escape(item.feature)}</td><td>{item.mean_abs_contribution}</td></tr>"
        for item in insights.impacts[:TOP_IMPACTS]
    )
    return (
        "<h2>Strongest push on individual predictions</h2>"
        "<p class='small muted'>Average size of each column's push on a single "
        f"prediction, measured on {insights.sample_size} held-out rows.</p>"
        f"<table><tr><th>Column</th><th>Average push</th></tr>{rows}</table>"
    )


def _warnings_section(meta: ModelMeta) -> str:
    if not meta.warnings:
        return ""
    items = "".join(f"<div class='warning'>{escape(w.message)}</div>" for w in meta.warnings)
    return f"<h2>Things to know</h2>{items}"


def _settings_section(meta: ModelMeta) -> str:
    rows = [f"<tr><td>Effort</td><td>{escape(meta.effort)}</td></tr>"]
    if meta.excluded_columns:
        skipped = ", ".join(escape(c.name) for c in meta.excluded_columns)
        rows.append(f"<tr><td>Columns left out</td><td>{skipped}</td></tr>")
    if meta.overrides is not None:
        for key, value in meta.overrides.xgb_params().items():
            rows.append(f"<tr><td>Tuned: {escape(key)}</td><td>{value}</td></tr>")
        for column, direction in meta.overrides.monotone_constraints.items():
            rule = "only rises" if direction == 1 else "only falls"
            rows.append(
                f"<tr><td>Direction rule</td><td>prediction {rule} with "
                f"{escape(column)}</td></tr>"
            )
    if meta.baseline_model_id:
        rows.append(
            f"<tr><td>Fine-tuned from</td><td>{escape(meta.baseline_model_id)}</td></tr>"
        )
    return f"<h2>Settings used</h2><table>{''.join(rows)}</table>"
